### ISSUE TITLE
Login and hash pages not found

### ISSUE THREAD

**Issue by chrismp** [simonw/datasette-auth-passwords#12]
Hello, I'm having trouble accessing `/-/password-tool` and `/-/login`.

On my Arch Linux machine in a virtual environment running Python 3.8.5, I ran `pip install datasette-auth-passwords`. 

I edited `metadata.json` so it includes:

	"plugins": {
		 "datasette-auth-passwords": {
		 	"someusername_password_hash": {
		 		"$env": "PASSWORD_HASH_1"
		 	}
		 }
	}

I used your [password tool](https://datasette-auth-passwords-demo.datasette.io/-/password-tool) to create a hash. 

In my terminal, I ran this:

    PASSWORD_HASH_1='pbkdf2_sha256$...' datasette serve databases/*.db -m metadata.json --template-dir=templates/ --debug

(The `...` represents the rest of the hash that I didn't paste here of course.)

When I navigated my browser to `http://127.0.0.1:8001/-/login` I was met with an "Error 404" page.

**Comment by simonw** [comment]
Hello, sorry for the late reply!

If you hit http://127.0.0.1:8001/-/plugins does it confirm that the plugin is installed?

Could you paste the output of http://127.0.0.1:8001/-/plugins and http://127.0.0.1:8001/-/versions and http://127.0.0.1:8001/-/metadata so I can see how your instance is configured?

**Comment by chrismp** [comment]
Outputs...

 http://127.0.0.1:8001/-/plugins:

```
[
    {
        "name": "datasette-auth-github",
        "static": false,
        "templates": true,
        "version": "0.12"
    },
    {
        "name": "datasette-auth-passwords",
        "static": false,
        "templates": true,
        "version": "0.3.1"
    }
]
```

http://127.0.0.1:8001/-/versions:

```
{
    "python": {
        "version": "3.8.5",
        "full": "3.8.5 (default, Jul 27 2020, 08:42:51) \n[GCC 10.1.0]"
    },
    "datasette": {
        "version": "0.28+153.g3c861f3"
    },
    "asgi": "3.0",
    "uvicorn": "0.11.1",
    "sqlite": {
        "version": "3.32.3",
        "fts_versions": [
            "FTS5",
            "FTS4",
            "FTS3"
        ],
        "extensions": {
            "json1": null
        },
        "compile_options": [
            "COMPILER=gcc-10.1.0",
            "ENABLE_COLUMN_METADATA",
            "ENABLE_DBSTAT_VTAB",
            "ENABLE_FTS3",
            "ENABLE_FTS3_TOKENIZER",
            "ENABLE_FTS4",
            "ENABLE_FTS5",
            "ENABLE_JSON1",
            "ENABLE_RTREE",
            "ENABLE_UNLOCK_NOTIFY",
            "HAVE_ISNAN",
            "MAX_EXPR_DEPTH=10000",
            "MAX_VARIABLE_NUMBER=250000",
            "SECURE_DELETE",
            "TEMP_STORE=1",
            "THREADSAFE=1"
        ]
    }
}
```

http://127.0.0.1:8001/-/metadata:

```
{
    "title": "My website",
    "about": "Chris P",
    "plugins": {
        "datasette-auth-passwords": {
            "someusername_password_hash": {
                "$env": "PASSWORD_HASH_1"
            }
        }
    },
    "databases": {...}
}
```

The dots in "databases" is shortened so I don't post all the databases of course.
The

**Comment by simonw** [comment]
Aha! It looks like you're running a pretty old version of Datasette: `0.28+153.g3c861f3` - try upgrading to Datasette 0.48.

I'll update the `setup.py` for this plugin to reflect the version of Datasette that it depends on (which I think is 0.44).
