### ISSUE TITLE
Is the user/passwd also applied to the json api ?

### ISSUE THREAD

**Issue by rezpe** [simonw/datasette-auth-passwords#18]
Hi,

If we want to access the json api of datasette, how could we use this plugin ? I understand the http basic authentication should be the option, something like:

```bash 
curl -u username:password url
```

and without the user/passwd, the api does not work. Please could you confirm ?

Thanks !

**Comment by simonw** [comment]
Yes, this plugin does affect the JSON API and you can use the basic authentication option to enable API access through that mechanism: https://github.com/simonw/datasette-auth-passwords#http-basic-authentication-option

You might also want to install the `datasette-auth-tokens` https://datasette.io/plugins/datasette-auth-tokens which can be installed at the same time as this plugin to enable authentication tokens for APIs.
