### ISSUE TITLE
hash stored in file adds a newline

### ISSUE THREAD

**Issue by publicmatt** [simonw/datasette-auth-passwords#22]
I'm trying to config the passwords from a file like so:

```json
{
    "plugins": {
        "datasette-auth-passwords": {
            "someusername_password_hash": {
                "$file": "/path/to/secret"
            }
        }
    }
}
```

but the hash that ultimately gets populated from that file includes a '\n' newline character at the end and fails the verify_password check.

Is this my own issue or is there something I'm going incorrectly?

**Comment by simonw** [comment]
I'm going to teach this plugin to strip the newline, though this is likely a bug in Datasette itself.

**Comment by simonw** [comment]
I'm not sure why this would happen- here's the relevant code in Datasette:

https://github.com/simonw/datasette/blob/7dd671310a4358e74663325336583746413f0993/datasette/utils/__init__.py#L1039-L1040

```python
        elif list(config.keys()) == ["$file"]:
            return open(list(config.values())[0]).read()
```

**Comment by publicmatt** [comment]
Thanks Simon!
